In [1]:
# Email Validation with Examples using re
## Numpy
## Pandas

In [32]:
# ravi@gmail.com

# @ Before

# minimum {8,15}

## using pattern
#[a-zA-Z]
#[a-zA-Z0-9._]
# @ after
#[a-z]{5,}
#.
#[a-z]{2,}

pattern = '^[a-zA-Z][A-Za-z0-9_.]{5,}[@][a-z.]{5,23}$'

In [34]:
s="s180751@rguktsklm.ac.in"
import re
re.search(pattern,s)

<re.Match object; span=(0, 23), match='s180751@rguktsklm.ac.in'>

In [23]:
f= open('emailid.txt','a')
count = int(input("how many create email ids"))
for i in range(1,count+1):
    email = input("enter email id")
    f.write(email+"\n")
f.close()

how many create email ids3
enter email idboppanaravi@gmail.com
enter email idravi@gmail.com
enter email idravisastry.b@apssdc.in


In [29]:
f= open('emailid.txt','r')
a=f.read()
for i in a.split():
    if re.search('^[a-zA-Z][A-Za-z0-9_.]{5,}[@][a-z.]{5,23}$',i):
        print(i,"valid")
    else:
        print(i,"Invalid")

boppanaravi@gmail.com Invalid
ravi@gmail.com Invalid
ravisastry.b@apssdc.in Invalid


In [45]:
s= 'vsdw14g2nm1bbj42vdsd422'
s1=0
count = 0
for i in s:
    i = i.rstrip()
    i2 = i.split()
    for i in range(len(i2)):
        if re.findall('[0-9]+',i2[i]):
            s1+=int(i2[i])
            count+=1
print(s1)

22


In [46]:
f=open('data2.txt','w')
s=input("enter the data")
f.write(s)
f.close()

enter the dataqfuqree2324dsd31hhhhh67nd


In [47]:
fh = open('data2.txt','r')
fh=fh.read()
s1=0
count = 0
for i in fh:
    i = i.rstrip()
    i2 = i.split()
    for i in range(len(i2)):
        if re.findall('[0-9]+',i2[i]):
            s1+=int(i2[i])
            count+=1
print(s1)

28


## Numpy

- Numpy stands for Numerical Python
- in this Consisting of Multidimensional array objects and collection for processing those arrays
- Using Numpy Mathematical and Logical Operation on array can be perform

In [50]:
import numpy as np
a=[1,2,3,4,5,6,7,8,9,10]# creating an numpy
a1=np.array(a)# single dimensional array
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a1.shape

(10,)

In [52]:
a1.size

10

In [53]:
a1.ndim

1

In [54]:
# 2 d array
s=np.array([[1,2,3,4,5],[6,7,8,9,10]])
s

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
s.ndim

2

In [56]:
s.shape

(2, 5)

In [57]:
s.size

10

In [58]:
# 3 d array
s1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
s1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
s1.shape

(3, 5)

In [60]:
s1.ndim

2

In [61]:
s1.size

15

In [62]:
# arange
data = ('range of numbers',np.arange(0,20))

In [63]:
data

('range of numbers',
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]))

In [64]:
data = ('range of even numbers',np.arange(0,20,2))

In [65]:
data

('range of even numbers', array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))

In [66]:
data = ('range of odd numbrs',np.arange(1,20,2))

In [67]:
data

('range of odd numbrs', array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]))

In [69]:
data = ('range of reverse numbers',np.arange(20,0,-1))
data

('range of reverse numbers',
 array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
         3,  2,  1]))

In [77]:
data=np.arange(1,21)
data.reshape(5,4)



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [94]:
# random
s= np.random.randn(2,3)
s

array([[-0.06741216,  2.39616008,  0.82426306],
       [ 1.66625535,  0.76417167,  0.45884714]])

In [95]:
s= np.random.randint(0,20,size=(2,6))

In [96]:
s

array([[ 8,  7, 18,  4, 17, 19],
       [ 8,  3, 16, 19,  7,  0]])

In [99]:
# linspace 
data = np.linspace(0,3,10)
data

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [100]:
data.resize(2,5)

In [101]:
data

array([[0.        , 0.33333333, 0.66666667, 1.        , 1.33333333],
       [1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ]])

In [105]:
# Built in functions in numpy
data = np.ones((4,3),int)
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [108]:
data = np.zeros((4,3),int)

In [109]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [112]:
#v-stack
n= np.ones([4,4],int)
n
np.vstack([n,n*10])

array([[ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [113]:
np.hstack([n,10*n])

array([[ 1,  1,  1,  1, 10, 10, 10, 10],
       [ 1,  1,  1,  1, 10, 10, 10, 10],
       [ 1,  1,  1,  1, 10, 10, 10, 10],
       [ 1,  1,  1,  1, 10, 10, 10, 10]])

In [114]:
# Dot : returns the dot product of two vectors
n=np.array([1,2,3,4,5])
n1=np.array([6,7,8,9,10])
n.dot(n1)

130

In [115]:
# Transpose
# T
# transpose()
n=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [116]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [117]:
n.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [118]:
n.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [119]:
# to crrate identity matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [120]:
# slicing
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
a[0]

array([1, 2, 3])

In [122]:
a[0,1:]

array([2, 3])

In [123]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [126]:
a[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
np.mean(a)

5.0

In [128]:
np.median(a)

5.0

In [129]:
np.max(a)

9

In [130]:
np.min(a)

1

## Pandas
- used for data Analysis
- 1.Series - single col and multiple rows
- 2.Dataframe - multiple rows and multiple cols

In [131]:
import pandas as pd
a = [10,20,30,40,50]
b = pd.Series(a)
b

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [132]:
b= pd.Series(a,index=["a","b","c","d","e"])
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [133]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [134]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [135]:
# 2. Data frames
a ={"cse":[10,20,30,40,50],'ece':[30,40,50,60,50],'eee':[50,60,30,40,80]}

In [137]:
df = pd.DataFrame(a,index=['rguktsklm','rguktnuzvid','rguktrkvalley','vasavi','vrsec'])
df

cse  ece  eee
rguktsklm       10   30   50
rguktnuzvid     20   40   60
rguktrkvalley   30   50   30
vasavi          40   60   40
vrsec           50   50   80

In [138]:
df['ece']

rguktsklm        30
rguktnuzvid      40
rguktrkvalley    50
vasavi           60
vrsec            50
Name: ece, dtype: int64

In [139]:
df[['cse','ece']]

cse  ece
rguktsklm       10   30
rguktnuzvid     20   40
rguktrkvalley   30   50
vasavi          40   60
vrsec           50   50

In [141]:
df.loc['rguktsklm']

cse    10
ece    30
eee    50
Name: rguktsklm, dtype: int64

In [142]:
df.loc[['vrsec','vasavi','rguktsklm']]

cse  ece  eee
vrsec       50   50   80
vasavi      40   60   40
rguktsklm   10   30   50

In [143]:
df.loc[["vrsec",'rguktsklm'],['cse','ece']]

cse  ece
vrsec       50   50
rguktsklm   10   30

In [144]:
df.iloc[0]

cse    10
ece    30
eee    50
Name: rguktsklm, dtype: int64

In [145]:
df.iloc[3]

cse    40
ece    60
eee    40
Name: vasavi, dtype: int64

In [147]:
df.iloc[0:,1:]

ece  eee
rguktsklm       30   50
rguktnuzvid     40   60
rguktrkvalley   50   30
vasavi          60   40
vrsec           50   80